server:
  port: 8081
spring:
  application: 
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/msv_userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: academy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL del Eureka Server

# Configuración
management:
  endpoints:
    web:
      exposure:
        include: "*"